### ISSUE TITLE
how to publish package to atmospherejs.com ?

### ISSUE THREAD

**Issue by achtan** [kadirahq/npm-base#7]
i configured package.js like this: https://github.com/DrMongo/dr-seeder/blob/master/package.js

dist/index.js http://pastebin.com/4KWXCDq2

but i'm getting error `exports is not defined` but i don't know how to fix it (dist/index.js is generated by babel)

**Comment by arunoda** [comment]
This is a NPM module and you need can't publish that to Atmosphere.
